services:
  - type: web
    name: kaveri-project
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT --app-dir backend"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
